//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraclePeeler
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate_lock_cluster_history
    {
        public int id { get; set; }
        public int rate_lock_cluster_id { get; set; }
        public byte division_id { get; set; }
        public string action { get; set; }
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual rate_lock_clusters rate_lock_clusters { get; set; }
    }
}
