//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraclePeeler
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate_lock_import_history
    {
        public long id { get; set; }
        public int old_rate_lock_id { get; set; }
        public int new_rate_lock_id { get; set; }
        public System.DateTime import_date { get; set; }
        public string imported_by { get; set; }
    
        public virtual rate_locks rate_locks { get; set; }
        public virtual rate_locks rate_locks1 { get; set; }
    }
}
