//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraclePeeler
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate_lock_fields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rate_lock_fields()
        {
            this.rate_lock_field_options = new HashSet<rate_lock_field_options>();
            this.rate_lock_rules = new HashSet<rate_lock_rules>();
        }
    
        public byte id { get; set; }
        public string name { get; set; }
        public string display_name { get; set; }
        public byte rate_lock_datatype_id { get; set; }
    
        public virtual rate_lock_datatypes rate_lock_datatypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rate_lock_field_options> rate_lock_field_options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rate_lock_rules> rate_lock_rules { get; set; }
    }
}
