//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraclePeeler
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate_lock_rule_groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rate_lock_rule_groups()
        {
            this.rate_lock_cluster_rules = new HashSet<rate_lock_cluster_rules>();
            this.rate_lock_period_rules = new HashSet<rate_lock_period_rules>();
            this.rate_lock_rules = new HashSet<rate_lock_rules>();
        }
    
        public int id { get; set; }
        public bool header { get; set; }
        public bool is_hidden { get; set; }
        public int rate_lock_folder_id { get; set; }
        public bool does_affect_target_profit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rate_lock_cluster_rules> rate_lock_cluster_rules { get; set; }
        public virtual rate_lock_folders rate_lock_folders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rate_lock_period_rules> rate_lock_period_rules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rate_lock_rules> rate_lock_rules { get; set; }
    }
}
