//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraclePeeler
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate_lock_field_options
    {
        public byte id { get; set; }
        public byte field_id { get; set; }
        public string value { get; set; }
    
        public virtual rate_lock_fields rate_lock_fields { get; set; }
    }
}
