//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraclePeeler
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate_lock_datatype_operators
    {
        public byte id { get; set; }
        public byte rate_lock_datatype_id { get; set; }
        public byte rate_lock_operator_id { get; set; }
    
        public virtual rate_lock_datatypes rate_lock_datatypes { get; set; }
        public virtual rate_lock_operators rate_lock_operators { get; set; }
    }
}
