//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraclePeeler
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate_lock_pricing_sheet_values
    {
        public int id { get; set; }
        public int rate_lock_pricing_sheet_product_id { get; set; }
        public string call_center_price { get; set; }
        public string branch_price { get; set; }
        public int rate_lock_pricing_sheet_id { get; set; }
        public string lock_period { get; set; }
        public string rate { get; set; }
        public string investor_pricing { get; set; }
        public string srp { get; set; }
    
        public virtual rate_lock_pricing_sheet rate_lock_pricing_sheet { get; set; }
    }
}
