//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiraclePeeler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrawfishEntities1 : DbContext
    {
        public CrawfishEntities1()
            : base("name=CrawfishEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rate_lock_cluster_divisions> rate_lock_cluster_divisions { get; set; }
        public virtual DbSet<rate_lock_cluster_history> rate_lock_cluster_history { get; set; }
        public virtual DbSet<rate_lock_cluster_rules> rate_lock_cluster_rules { get; set; }
        public virtual DbSet<rate_lock_clusters> rate_lock_clusters { get; set; }
        public virtual DbSet<rate_lock_colors> rate_lock_colors { get; set; }
        public virtual DbSet<rate_lock_datatype_operators> rate_lock_datatype_operators { get; set; }
        public virtual DbSet<rate_lock_datatypes> rate_lock_datatypes { get; set; }
        public virtual DbSet<rate_lock_encompass_statuses> rate_lock_encompass_statuses { get; set; }
        public virtual DbSet<rate_lock_field_options> rate_lock_field_options { get; set; }
        public virtual DbSet<rate_lock_fields> rate_lock_fields { get; set; }
        public virtual DbSet<rate_lock_folders> rate_lock_folders { get; set; }
        public virtual DbSet<rate_lock_import_history> rate_lock_import_history { get; set; }
        public virtual DbSet<rate_lock_loan_info> rate_lock_loan_info { get; set; }
        public virtual DbSet<rate_lock_manual_product_codes> rate_lock_manual_product_codes { get; set; }
        public virtual DbSet<rate_lock_manual_product_codes_history> rate_lock_manual_product_codes_history { get; set; }
        public virtual DbSet<rate_lock_notifications> rate_lock_notifications { get; set; }
        public virtual DbSet<rate_lock_operators> rate_lock_operators { get; set; }
        public virtual DbSet<rate_lock_period_rules> rate_lock_period_rules { get; set; }
        public virtual DbSet<rate_lock_pricing_sheet> rate_lock_pricing_sheet { get; set; }
        public virtual DbSet<rate_lock_pricing_sheet_values> rate_lock_pricing_sheet_values { get; set; }
        public virtual DbSet<rate_lock_reporting_fields> rate_lock_reporting_fields { get; set; }
        public virtual DbSet<rate_lock_rule_groups> rate_lock_rule_groups { get; set; }
        public virtual DbSet<rate_lock_rule_types> rate_lock_rule_types { get; set; }
        public virtual DbSet<rate_lock_rule_values> rate_lock_rule_values { get; set; }
        public virtual DbSet<rate_lock_rule_versions> rate_lock_rule_versions { get; set; }
        public virtual DbSet<rate_lock_rules> rate_lock_rules { get; set; }
        public virtual DbSet<rate_lock_statuses> rate_lock_statuses { get; set; }
        public virtual DbSet<rate_lock_super_users> rate_lock_super_users { get; set; }
        public virtual DbSet<rate_lock_types> rate_lock_types { get; set; }
        public virtual DbSet<rate_lock_uploads> rate_lock_uploads { get; set; }
        public virtual DbSet<rate_locks> rate_locks { get; set; }
    }
}
